# This file has been generated by node2nix 1.7.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "loose-envify-1.4.0" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz";
        sha512 = "lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "prop-types-15.7.2" = {
      name = "prop-types";
      packageName = "prop-types";
      version = "15.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prop-types/-/prop-types-15.7.2.tgz";
        sha512 = "8QQikdH7//R2vurIJSutZ1smHYTcLpRWEOlHnzcWHmBYrOGUysKwSsrC89BCiFj3CbrfJ/nXFdJepOVrY1GCHQ==";
      };
    };
    "react-is-16.13.0" = {
      name = "react-is";
      packageName = "react-is";
      version = "16.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-is/-/react-is-16.13.0.tgz";
        sha512 = "GFMtL0vHkiBv9HluwNZTggSn/sCyEt9n02aM0dSAjGGyqyNlAyftYm4phPxdvCigG15JreC5biwxCgTAJZ7yAA==";
      };
    };
    "scheduler-0.19.0" = {
      name = "scheduler";
      packageName = "scheduler";
      version = "0.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/scheduler/-/scheduler-0.19.0.tgz";
        sha512 = "xowbVaTPe9r7y7RUejcK73/j8tt2jfiyTednOvHbA8JoClvMYCp+r8QegLwK/n8zWQAtZb1fFnER4XLBZXrCxA==";
      };
    };
  };
in
{
  react = nodeEnv.buildNodePackage {
    name = "react";
    packageName = "react";
    version = "16.13.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/react/-/react-16.13.0.tgz";
      sha512 = "TSavZz2iSLkq5/oiE7gnFzmURKZMltmi193rm5HEoUDAXpzT9Kzw6oNZnGoai/4+fUnm7FqS5dwgUL34TujcWQ==";
    };
    dependencies = [
      sources."js-tokens-4.0.0"
      sources."loose-envify-1.4.0"
      sources."object-assign-4.1.1"
      sources."prop-types-15.7.2"
      sources."react-is-16.13.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "React is a JavaScript library for building user interfaces.";
      homepage = https://reactjs.org/;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  react-dom = nodeEnv.buildNodePackage {
    name = "react-dom";
    packageName = "react-dom";
    version = "16.13.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/react-dom/-/react-dom-16.13.0.tgz";
      sha512 = "y09d2c4cG220DzdlFkPTnVvGTszVvNpC73v+AaLGLHbkpy3SSgvYq8x0rNwPJ/Rk/CicTNgk0hbHNw1gMEZAXg==";
    };
    dependencies = [
      sources."js-tokens-4.0.0"
      sources."loose-envify-1.4.0"
      sources."object-assign-4.1.1"
      sources."prop-types-15.7.2"
      sources."react-is-16.13.0"
      sources."scheduler-0.19.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "React package for working with the DOM.";
      homepage = https://reactjs.org/;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "normalize.css" = nodeEnv.buildNodePackage {
    name = "normalize.css";
    packageName = "normalize.css";
    version = "8.0.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/normalize.css/-/normalize.css-8.0.1.tgz";
      sha512 = "qizSNPO93t1YUuUhP22btGOo3chcvDFqFaj2TRybP0DMxkHOCTYwp3n34fel4a31ORXy4m1Xq0Gyqpb5m33qIg==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "A modern alternative to CSS resets";
      homepage = https://necolas.github.io/normalize.css;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}