# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@types/q-1.5.4" = {
      name = "_at_types_slash_q";
      packageName = "@types/q";
      version = "1.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/q/-/q-1.5.4.tgz";
        sha512 = "1HcDas8SEj4z1Wc696tH56G8OlRaH/sqZOynNNB+HF0WOeXPaxTtbYzJY2oEfiUxjSKjhCKr+MvR7dCHcEelug==";
      };
    };
    "alphanum-sort-1.0.2" = {
      name = "alphanum-sort";
      packageName = "alphanum-sort";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/alphanum-sort/-/alphanum-sort-1.0.2.tgz";
        sha1 = "97a1119649b211ad33691d9f9f486a8ec9fbe0a3";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
      };
    };
    "boolbase-1.0.0" = {
      name = "boolbase";
      packageName = "boolbase";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/boolbase/-/boolbase-1.0.0.tgz";
        sha1 = "68dff5fbe60c51eb37725ea9e3ed310dcc1e776e";
      };
    };
    "browserslist-4.16.3" = {
      name = "browserslist";
      packageName = "browserslist";
      version = "4.16.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserslist/-/browserslist-4.16.3.tgz";
        sha512 = "vIyhWmIkULaq04Gt93txdh+j02yX/JzlyhLYbV3YQCn/zvES3JnY7TifHHvvr1w5hTDluNKMkV05cs4vy8Q7sw==";
      };
    };
    "call-bind-1.0.2" = {
      name = "call-bind";
      packageName = "call-bind";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/call-bind/-/call-bind-1.0.2.tgz";
        sha512 = "7O+FbCihrB5WGbFYesctwmTKae6rOiIzmz1icreWJ+0aA7LJfuqhEso2T9ncpcFtzMQtzXf2QGGueWJGTYsqrA==";
      };
    };
    "caller-callsite-2.0.0" = {
      name = "caller-callsite";
      packageName = "caller-callsite";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caller-callsite/-/caller-callsite-2.0.0.tgz";
        sha1 = "847e0fce0a223750a9a027c54b33731ad3154134";
      };
    };
    "caller-path-2.0.0" = {
      name = "caller-path";
      packageName = "caller-path";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caller-path/-/caller-path-2.0.0.tgz";
        sha1 = "468f83044e369ab2010fac5f06ceee15bb2cb1f4";
      };
    };
    "callsites-2.0.0" = {
      name = "callsites";
      packageName = "callsites";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/callsites/-/callsites-2.0.0.tgz";
        sha1 = "06eb84f00eea413da86affefacbffb36093b3c50";
      };
    };
    "caniuse-api-3.0.0" = {
      name = "caniuse-api";
      packageName = "caniuse-api";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caniuse-api/-/caniuse-api-3.0.0.tgz";
        sha512 = "bsTwuIg/BZZK/vreVTYYbSWoe2F+71P7K5QGEX+pT250DZbfU1MQ5prOKpPR+LL6uWKK3KMwMCAS74QB3Um1uw==";
      };
    };
    "caniuse-lite-1.0.30001192" = {
      name = "caniuse-lite";
      packageName = "caniuse-lite";
      version = "1.0.30001192";
      src = fetchurl {
        url = "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001192.tgz";
        sha512 = "63OrUnwJj5T1rUmoyqYTdRWBqFFxZFlyZnRRjDR8NSUQFB6A+j/uBORU/SyJ5WzDLg4SPiZH40hQCBNdZ/jmAw==";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "coa-2.0.2" = {
      name = "coa";
      packageName = "coa";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/coa/-/coa-2.0.2.tgz";
        sha512 = "q5/jG+YQnSy4nRTV4F7lPepBJZ8qBNJJDBuJdoejDyLXgmL7IEo+Le2JDZudFTFt7mrCqIRaSjws4ygRCTCAXA==";
      };
    };
    "color-3.1.3" = {
      name = "color";
      packageName = "color";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color/-/color-3.1.3.tgz";
        sha512 = "xgXAcTHa2HeFCGLE9Xs/R82hujGtu9Jd9x4NW3T34+OMs7VoPsjwzRczKHvTAHeJwWFwX5j15+MgAppE8ztObQ==";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha1 = "a7d0558bd89c42f795dd42328f740831ca53bc25";
      };
    };
    "color-string-1.5.4" = {
      name = "color-string";
      packageName = "color-string";
      version = "1.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-string/-/color-string-1.5.4.tgz";
        sha512 = "57yF5yt8Xa3czSEW1jfQDE79Idk0+AkN/4KWad6tbdxUmAs3MvjxlWSWD4deYytcRfoZ9nhKyFl1kj5tBvidbw==";
      };
    };
    "colorette-1.2.2" = {
      name = "colorette";
      packageName = "colorette";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/colorette/-/colorette-1.2.2.tgz";
        sha512 = "MKGMzyfeuutC/ZJ1cba9NqcNpfeqMUcYmyF1ZFY6/Cn7CNSAKx6a+s48sqLqyAiZuaP2TcqMhoo+dlwFnVxT9w==";
      };
    };
    "cosmiconfig-5.2.1" = {
      name = "cosmiconfig";
      packageName = "cosmiconfig";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cosmiconfig/-/cosmiconfig-5.2.1.tgz";
        sha512 = "H65gsXo1SKjf8zmrJ67eJk8aIRKV5ff2D4uKZIBZShbhGSpEmsQOPW/SKMKYhSTrqR7ufy6RP69rPogdaPh/kA==";
      };
    };
    "css-color-names-0.0.4" = {
      name = "css-color-names";
      packageName = "css-color-names";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-color-names/-/css-color-names-0.0.4.tgz";
        sha1 = "808adc2e79cf84738069b646cb20ec27beb629e0";
      };
    };
    "css-declaration-sorter-4.0.1" = {
      name = "css-declaration-sorter";
      packageName = "css-declaration-sorter";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-declaration-sorter/-/css-declaration-sorter-4.0.1.tgz";
        sha512 = "BcxQSKTSEEQUftYpBVnsH4SF05NTuBokb19/sBt6asXGKZ/6VP7PLG1CBCkFDYOnhXhPh0jMhO6xZ71oYHXHBA==";
      };
    };
    "css-select-2.1.0" = {
      name = "css-select";
      packageName = "css-select";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-select/-/css-select-2.1.0.tgz";
        sha512 = "Dqk7LQKpwLoH3VovzZnkzegqNSuAziQyNZUcrdDM401iY+R5NkGBXGmtO05/yaXQziALuPogeG0b7UAgjnTJTQ==";
      };
    };
    "css-select-base-adapter-0.1.1" = {
      name = "css-select-base-adapter";
      packageName = "css-select-base-adapter";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-select-base-adapter/-/css-select-base-adapter-0.1.1.tgz";
        sha512 = "jQVeeRG70QI08vSTwf1jHxp74JoZsr2XSgETae8/xC8ovSnL2WF87GTLO86Sbwdt2lK4Umg4HnnwMO4YF3Ce7w==";
      };
    };
    "css-tree-1.0.0-alpha.37" = {
      name = "css-tree";
      packageName = "css-tree";
      version = "1.0.0-alpha.37";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-tree/-/css-tree-1.0.0-alpha.37.tgz";
        sha512 = "DMxWJg0rnz7UgxKT0Q1HU/L9BeJI0M6ksor0OgqOnF+aRCDWg/N2641HmVyU9KVIu0OVVWOb2IpC9A+BJRnejg==";
      };
    };
    "css-tree-1.1.2" = {
      name = "css-tree";
      packageName = "css-tree";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-tree/-/css-tree-1.1.2.tgz";
        sha512 = "wCoWush5Aeo48GLhfHPbmvZs59Z+M7k5+B1xDnXbdWNcEF423DoFdqSWE0PM5aNk5nI5cp1q7ms36zGApY/sKQ==";
      };
    };
    "css-what-3.4.2" = {
      name = "css-what";
      packageName = "css-what";
      version = "3.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-what/-/css-what-3.4.2.tgz";
        sha512 = "ACUm3L0/jiZTqfzRM3Hi9Q8eZqd6IK37mMWPLz9PJxkLWllYeRf+EHUSHYEtFop2Eqytaq1FizFVh7XfBnXCDQ==";
      };
    };
    "cssesc-3.0.0" = {
      name = "cssesc";
      packageName = "cssesc";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssesc/-/cssesc-3.0.0.tgz";
        sha512 = "/Tb/JcjK111nNScGob5MNtsntNM1aCNUDipB/TkwZFhyDrrE47SOx/18wF2bbjgc3ZzCSKW1T5nt5EbFoAz/Vg==";
      };
    };
    "cssnano-preset-default-4.0.7" = {
      name = "cssnano-preset-default";
      packageName = "cssnano-preset-default";
      version = "4.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssnano-preset-default/-/cssnano-preset-default-4.0.7.tgz";
        sha512 = "x0YHHx2h6p0fCl1zY9L9roD7rnlltugGu7zXSKQx6k2rYw0Hi3IqxcoAGF7u9Q5w1nt7vK0ulxV8Lo+EvllGsA==";
      };
    };
    "cssnano-util-get-arguments-4.0.0" = {
      name = "cssnano-util-get-arguments";
      packageName = "cssnano-util-get-arguments";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssnano-util-get-arguments/-/cssnano-util-get-arguments-4.0.0.tgz";
        sha1 = "ed3a08299f21d75741b20f3b81f194ed49cc150f";
      };
    };
    "cssnano-util-get-match-4.0.0" = {
      name = "cssnano-util-get-match";
      packageName = "cssnano-util-get-match";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssnano-util-get-match/-/cssnano-util-get-match-4.0.0.tgz";
        sha1 = "c0e4ca07f5386bb17ec5e52250b4f5961365156d";
      };
    };
    "cssnano-util-raw-cache-4.0.1" = {
      name = "cssnano-util-raw-cache";
      packageName = "cssnano-util-raw-cache";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssnano-util-raw-cache/-/cssnano-util-raw-cache-4.0.1.tgz";
        sha512 = "qLuYtWK2b2Dy55I8ZX3ky1Z16WYsx544Q0UWViebptpwn/xDBmog2TLg4f+DBMg1rJ6JDWtn96WHbOKDWt1WQA==";
      };
    };
    "cssnano-util-same-parent-4.0.1" = {
      name = "cssnano-util-same-parent";
      packageName = "cssnano-util-same-parent";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssnano-util-same-parent/-/cssnano-util-same-parent-4.0.1.tgz";
        sha512 = "WcKx5OY+KoSIAxBW6UBBRay1U6vkYheCdjyVNDm85zt5K9mHoGOfsOsqIszfAqrQQFIIKgjh2+FDgIj/zsl21Q==";
      };
    };
    "csso-4.2.0" = {
      name = "csso";
      packageName = "csso";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/csso/-/csso-4.2.0.tgz";
        sha512 = "wvlcdIbf6pwKEk7vHj8/Bkc0B4ylXZruLvOgs9doS5eOsOpuodOV2zJChSpkp+pRpYQLQMeF04nr3Z68Sta9jA==";
      };
    };
    "define-properties-1.1.3" = {
      name = "define-properties";
      packageName = "define-properties";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-properties/-/define-properties-1.1.3.tgz";
        sha512 = "3MqfYKj2lLzdMSf8ZIZE/V+Zuy+BgD6f164e8K2w7dgnpKArBDerGYpM46IYYcjnkdPNMjPk9A6VFB8+3SKlXQ==";
      };
    };
    "dom-serializer-0.2.2" = {
      name = "dom-serializer";
      packageName = "dom-serializer";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-serializer/-/dom-serializer-0.2.2.tgz";
        sha512 = "2/xPb3ORsQ42nHYiSunXkDjPLBaEj/xTwUO4B7XCZQTRk7EBtTOPaygh10YAAh2OI1Qrp6NWfpAhzswj0ydt9g==";
      };
    };
    "domelementtype-1.3.1" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-1.3.1.tgz";
        sha512 = "BSKB+TSpMpFI/HOxCNr1O8aMOTZ8hT3pM3GQ0w/mWRmkhEDSFJkkyzz4XQsBV44BChwGkrDfMyjVD0eA2aFV3w==";
      };
    };
    "domelementtype-2.1.0" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-2.1.0.tgz";
        sha512 = "LsTgx/L5VpD+Q8lmsXSHW2WpA+eBlZ9HPf3erD1IoPF00/3JKHZ3BknUVA2QGDNu69ZNmyFmCWBSO45XjYKC5w==";
      };
    };
    "domutils-1.7.0" = {
      name = "domutils";
      packageName = "domutils";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domutils/-/domutils-1.7.0.tgz";
        sha512 = "Lgd2XcJ/NjEw+7tFvfKxOzCYKZsdct5lczQ2ZaQY8Djz7pfAD3Gbp8ySJWtreII/vDlMVmxwa6pHmdxIYgttDg==";
      };
    };
    "dot-prop-5.3.0" = {
      name = "dot-prop";
      packageName = "dot-prop";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dot-prop/-/dot-prop-5.3.0.tgz";
        sha512 = "QM8q3zDe58hqUqjraQOmzZ1LIH9SWQJTlEKCH4kJ2oQvLZk7RbQXvtDM2XEq3fwkV9CCvvH4LA0AV+ogFsBM2Q==";
      };
    };
    "electron-to-chromium-1.3.674" = {
      name = "electron-to-chromium";
      packageName = "electron-to-chromium";
      version = "1.3.674";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-to-chromium/-/electron-to-chromium-1.3.674.tgz";
        sha512 = "DBmEKRVYLZAoQSW+AmLcTF5Bpwhk4RUkobtzXVDlfPPYIlbsH3Jfg3QbBjAfFcRARzMIo4YiMhp3N+RnMuo1Eg==";
      };
    };
    "entities-2.2.0" = {
      name = "entities";
      packageName = "entities";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-2.2.0.tgz";
        sha512 = "p92if5Nz619I0w+akJrLZH0MX0Pb5DX39XOwQTtXSdQQOaYH03S1uIQp4mhOZtAXrxq4ViO67YTiLBo2638o9A==";
      };
    };
    "error-ex-1.3.2" = {
      name = "error-ex";
      packageName = "error-ex";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/error-ex/-/error-ex-1.3.2.tgz";
        sha512 = "7dFHNmqeFSEt2ZBsCriorKnn3Z2pj+fd9kmI6QoWw4//DL+icEBfc0U7qJCisqrTsKTjw4fNFy2pW9OqStD84g==";
      };
    };
    "es-abstract-1.17.7" = {
      name = "es-abstract";
      packageName = "es-abstract";
      version = "1.17.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-abstract/-/es-abstract-1.17.7.tgz";
        sha512 = "VBl/gnfcJ7OercKA9MVaegWsBHFjV492syMudcnQZvt/Dw8ezpcOHYZXa/J96O8vx+g4x65YKhxOwDUh63aS5g==";
      };
    };
    "es-abstract-1.18.0-next.2" = {
      name = "es-abstract";
      packageName = "es-abstract";
      version = "1.18.0-next.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-abstract/-/es-abstract-1.18.0-next.2.tgz";
        sha512 = "Ih4ZMFHEtZupnUh6497zEL4y2+w8+1ljnCyaTa+adcoafI1GOvMwFlDjBLfWR7y9VLfrjRJe9ocuHY1PSR9jjw==";
      };
    };
    "es-to-primitive-1.2.1" = {
      name = "es-to-primitive";
      packageName = "es-to-primitive";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-to-primitive/-/es-to-primitive-1.2.1.tgz";
        sha512 = "QCOllgZJtaUo9miYBcLChTUaHNjJF3PYs1VidD7AwiEj1kYxKeQTctLAezAOH5ZKRH0g2IgPn6KwB4IT8iRpvA==";
      };
    };
    "escalade-3.1.1" = {
      name = "escalade";
      packageName = "escalade";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/escalade/-/escalade-3.1.1.tgz";
        sha512 = "k0er2gUkLf8O0zKJiAhmkTnJlTvINGv7ygDNPbeIsX/TJjGJZHuh9B2UxbsaEkmlEo9MfhrSzmhIlhRlI2GXnw==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "esprima-4.0.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
        sha512 = "eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "get-intrinsic-1.1.1" = {
      name = "get-intrinsic";
      packageName = "get-intrinsic";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-intrinsic/-/get-intrinsic-1.1.1.tgz";
        sha512 = "kWZrnVM42QCiEA2Ig1bG8zjoIMOgxWwYCEeNdwY6Tv/cOSeGpcoX4pXHfKUxNKVoArnrEr2e9srnAxxGIraS9Q==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha1 = "b5d454dc2199ae225699f3467e5a07f3b955bafd";
      };
    };
    "has-symbols-1.0.1" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.0.1.tgz";
        sha512 = "PLcsoqu++dmEIZB+6totNFKq/7Do+Z0u4oT0zKOJNl3lYK6vGwwu2hjHs+68OEZbTjiUE9bgOABXbP/GvrS0Kg==";
      };
    };
    "hex-color-regex-1.1.0" = {
      name = "hex-color-regex";
      packageName = "hex-color-regex";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hex-color-regex/-/hex-color-regex-1.1.0.tgz";
        sha512 = "l9sfDFsuqtOqKDsQdqrMRk0U85RZc0RtOR9yPI7mRVOa4FsR/BVnZ0shmQRM96Ji99kYZP/7hn1cedc1+ApsTQ==";
      };
    };
    "hsl-regex-1.0.0" = {
      name = "hsl-regex";
      packageName = "hsl-regex";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hsl-regex/-/hsl-regex-1.0.0.tgz";
        sha1 = "d49330c789ed819e276a4c0d272dffa30b18fe6e";
      };
    };
    "hsla-regex-1.0.0" = {
      name = "hsla-regex";
      packageName = "hsla-regex";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hsla-regex/-/hsla-regex-1.0.0.tgz";
        sha1 = "c1ce7a3168c8c6614033a4b5f7877f3b225f9c38";
      };
    };
    "html-comment-regex-1.1.2" = {
      name = "html-comment-regex";
      packageName = "html-comment-regex";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/html-comment-regex/-/html-comment-regex-1.1.2.tgz";
        sha512 = "P+M65QY2JQ5Y0G9KKdlDpo0zK+/OHptU5AaBwUfAIDJZk1MYf32Frm84EcOytfJE0t5JvkAnKlmjsXDnWzCJmQ==";
      };
    };
    "import-fresh-2.0.0" = {
      name = "import-fresh";
      packageName = "import-fresh";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/import-fresh/-/import-fresh-2.0.0.tgz";
        sha1 = "d81355c15612d386c61f9ddd3922d4304822a546";
      };
    };
    "indexes-of-1.0.1" = {
      name = "indexes-of";
      packageName = "indexes-of";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/indexes-of/-/indexes-of-1.0.1.tgz";
        sha1 = "f30f716c8e2bd346c7b67d3df3915566a7c05607";
      };
    };
    "is-absolute-url-2.1.0" = {
      name = "is-absolute-url";
      packageName = "is-absolute-url";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-absolute-url/-/is-absolute-url-2.1.0.tgz";
        sha1 = "50530dfb84fcc9aa7dbe7852e83a37b93b9f2aa6";
      };
    };
    "is-arrayish-0.2.1" = {
      name = "is-arrayish";
      packageName = "is-arrayish";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.2.1.tgz";
        sha1 = "77c99840527aa8ecb1a8ba697b80645a7a926a9d";
      };
    };
    "is-arrayish-0.3.2" = {
      name = "is-arrayish";
      packageName = "is-arrayish";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.3.2.tgz";
        sha512 = "eVRqCvVlZbuw3GrM63ovNSNAeA1K16kaR/LRY/92w0zxQ5/1YzwblUX652i4Xs9RwAGjW9d9y6X88t8OaAJfWQ==";
      };
    };
    "is-callable-1.2.3" = {
      name = "is-callable";
      packageName = "is-callable";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-callable/-/is-callable-1.2.3.tgz";
        sha512 = "J1DcMe8UYTBSrKezuIUTUwjXsho29693unXM2YhJUTR2txK/eG47bvNa/wipPFmZFgr/N6f1GA66dv0mEyTIyQ==";
      };
    };
    "is-color-stop-1.1.0" = {
      name = "is-color-stop";
      packageName = "is-color-stop";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-color-stop/-/is-color-stop-1.1.0.tgz";
        sha1 = "cfff471aee4dd5c9e158598fbe12967b5cdad345";
      };
    };
    "is-date-object-1.0.2" = {
      name = "is-date-object";
      packageName = "is-date-object";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-date-object/-/is-date-object-1.0.2.tgz";
        sha512 = "USlDT524woQ08aoZFzh3/Z6ch9Y/EWXEHQ/AaRN0SkKq4t2Jw2R2339tSXmwuVoY7LLlBCbOIlx2myP/L5zk0g==";
      };
    };
    "is-directory-0.3.1" = {
      name = "is-directory";
      packageName = "is-directory";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-directory/-/is-directory-0.3.1.tgz";
        sha1 = "61339b6f2475fc772fd9c9d83f5c8575dc154ae1";
      };
    };
    "is-negative-zero-2.0.1" = {
      name = "is-negative-zero";
      packageName = "is-negative-zero";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-negative-zero/-/is-negative-zero-2.0.1.tgz";
        sha512 = "2z6JzQvZRa9A2Y7xC6dQQm4FSTSTNWjKIYYTt4246eMTJmIo0Q+ZyOsU66X8lxK1AbB92dFeglPLrhwpeRKO6w==";
      };
    };
    "is-obj-2.0.0" = {
      name = "is-obj";
      packageName = "is-obj";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-obj/-/is-obj-2.0.0.tgz";
        sha512 = "drqDG3cbczxxEJRoOXcOjtdp1J/lyp1mNn0xaznRs8+muBhgQcrnbspox5X5fOw0HnMnbfDzvnEMEtqDEJEo8w==";
      };
    };
    "is-regex-1.1.2" = {
      name = "is-regex";
      packageName = "is-regex";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-regex/-/is-regex-1.1.2.tgz";
        sha512 = "axvdhb5pdhEVThqJzYXwMlVuZwC+FF2DpcOhTS+y/8jVq4trxyPgfcwIxIKiyeuLlSQYKkmUaPQJ8ZE4yNKXDg==";
      };
    };
    "is-resolvable-1.1.0" = {
      name = "is-resolvable";
      packageName = "is-resolvable";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-resolvable/-/is-resolvable-1.1.0.tgz";
        sha512 = "qgDYXFSR5WvEfuS5dMj6oTMEbrrSaM0CrFk2Yiq/gXnBvD9pMa2jGXxyhGLfvhZpuMZe18CJpFxAt3CRs42NMg==";
      };
    };
    "is-svg-3.0.0" = {
      name = "is-svg";
      packageName = "is-svg";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-svg/-/is-svg-3.0.0.tgz";
        sha512 = "gi4iHK53LR2ujhLVVj+37Ykh9GLqYHX6JOVXbLAucaG/Cqw9xwdFOjDM2qeifLs1sF1npXXFvDu0r5HNgCMrzQ==";
      };
    };
    "is-symbol-1.0.3" = {
      name = "is-symbol";
      packageName = "is-symbol";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-symbol/-/is-symbol-1.0.3.tgz";
        sha512 = "OwijhaRSgqvhm/0ZdAcXNZt9lYdKFpcRDT5ULUuYXPoT794UNOdU+gpT6Rzo7b4V2HUl/op6GqY894AZwv9faQ==";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "js-yaml-3.14.1" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "3.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.14.1.tgz";
        sha512 = "okMH7OXXJ7YrN9Ok3/SXrnu4iX9yOk+25nqX4imS2npuvTYDmo/QEZoqwZkYaIDk3jVvBOTOIEgEhaLOynBS9g==";
      };
    };
    "json-parse-better-errors-1.0.2" = {
      name = "json-parse-better-errors";
      packageName = "json-parse-better-errors";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-parse-better-errors/-/json-parse-better-errors-1.0.2.tgz";
        sha512 = "mrqyZKfX5EhL7hvqcV6WG1yYjnjeuYDzDhhcAAUrq8Po85NBQBJP+ZDUT75qZQ98IkUoBqdkExkukOU7Ts2wrw==";
      };
    };
    "lodash.memoize-4.1.2" = {
      name = "lodash.memoize";
      packageName = "lodash.memoize";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.memoize/-/lodash.memoize-4.1.2.tgz";
        sha1 = "bcc6c49a42a2840ed997f323eada5ecd182e0bfe";
      };
    };
    "lodash.uniq-4.5.0" = {
      name = "lodash.uniq";
      packageName = "lodash.uniq";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.uniq/-/lodash.uniq-4.5.0.tgz";
        sha1 = "d0225373aeb652adc1bc82e4945339a842754773";
      };
    };
    "loose-envify-1.4.0" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz";
        sha512 = "lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==";
      };
    };
    "mdn-data-2.0.14" = {
      name = "mdn-data";
      packageName = "mdn-data";
      version = "2.0.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdn-data/-/mdn-data-2.0.14.tgz";
        sha512 = "dn6wd0uw5GsdswPFfsgMp5NSB0/aDe6fK94YJV/AJDYXL6HVLWBsxeq7js7Ad+mU2K9LAlwpk6kN2D5mwCPVow==";
      };
    };
    "mdn-data-2.0.4" = {
      name = "mdn-data";
      packageName = "mdn-data";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdn-data/-/mdn-data-2.0.4.tgz";
        sha512 = "iV3XNKw06j5Q7mi6h+9vbx23Tv7JkjEVgKHW4pimwyDGWm0OIQntJJ+u1C6mg6mK1EaTv42XQ7w76yuzH7M2cA==";
      };
    };
    "minimist-1.2.5" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.5.tgz";
        sha512 = "FM9nNUYrRBAELZQT3xeZQ7fmMOBg6nWNmJKTcgsJeaLstP/UODVpGsr5OhXhhXg6f+qtJ8uiZ+PUxkDWcgIXLw==";
      };
    };
    "mkdirp-0.5.5" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.5.tgz";
        sha512 = "NKmAlESf6jMGym1++R0Ra7wvhV+wFW63FaSOFPwRahvea0gMUcGUhVeAg/0BC0wiv9ih5NYPB1Wn1UEI1/L+xQ==";
      };
    };
    "node-releases-1.1.71" = {
      name = "node-releases";
      packageName = "node-releases";
      version = "1.1.71";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-releases/-/node-releases-1.1.71.tgz";
        sha512 = "zR6HoT6LrLCRBwukmrVbHv0EpEQjksO6GmFcZQQuCAy139BEsoVKPYnf3jongYW83fAa1torLGYwxxky/p28sg==";
      };
    };
    "normalize-url-3.3.0" = {
      name = "normalize-url";
      packageName = "normalize-url";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-url/-/normalize-url-3.3.0.tgz";
        sha512 = "U+JJi7duF1o+u2pynbp2zXDW2/PADgC30f0GsHZtRh+HOcXHnw137TrNlyxxRvWW5fjKd3bcLHPxofWuCjaeZg==";
      };
    };
    "nth-check-1.0.2" = {
      name = "nth-check";
      packageName = "nth-check";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/nth-check/-/nth-check-1.0.2.tgz";
        sha512 = "WeBOdju8SnzPN5vTUJYxYUxLeXpCaVP5i5e0LF8fg7WORF2Wd7wFX/pk0tYZk7s8T+J7VLy0Da6J1+wCT0AtHg==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "object-inspect-1.9.0" = {
      name = "object-inspect";
      packageName = "object-inspect";
      version = "1.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-inspect/-/object-inspect-1.9.0.tgz";
        sha512 = "i3Bp9iTqwhaLZBxGkRfo5ZbE07BQRT7MGu8+nNgwW9ItGp1TzCTw2DLEoWwjClxBjOFI/hWljTAmYGCEwmtnOw==";
      };
    };
    "object-keys-1.1.1" = {
      name = "object-keys";
      packageName = "object-keys";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-keys/-/object-keys-1.1.1.tgz";
        sha512 = "NuAESUOUMrlIXOfHKzD6bpPu3tYt3xvjNdRIQ+FeT0lNb4K8WR70CaDxhuNguS2XG+GjkyMwOzsN5ZktImfhLA==";
      };
    };
    "object.assign-4.1.2" = {
      name = "object.assign";
      packageName = "object.assign";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.assign/-/object.assign-4.1.2.tgz";
        sha512 = "ixT2L5THXsApyiUPYKmW+2EHpXXe5Ii3M+f4e+aJFAHao5amFRW6J0OO6c/LU8Be47utCx2GL89hxGB6XSmKuQ==";
      };
    };
    "object.getownpropertydescriptors-2.1.2" = {
      name = "object.getownpropertydescriptors";
      packageName = "object.getownpropertydescriptors";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.getownpropertydescriptors/-/object.getownpropertydescriptors-2.1.2.tgz";
        sha512 = "WtxeKSzfBjlzL+F9b7M7hewDzMwy+C8NRssHd1YrNlzHzIDrXcXiNOMrezdAEM4UXixgV+vvnyBeN7Rygl2ttQ==";
      };
    };
    "object.values-1.1.3" = {
      name = "object.values";
      packageName = "object.values";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.values/-/object.values-1.1.3.tgz";
        sha512 = "nkF6PfDB9alkOUxpf1HNm/QlkeW3SReqL5WXeBLpEJJnlPSvRaDQpW3gQTksTN3fgJX4hL42RzKyOin6ff3tyw==";
      };
    };
    "parse-json-4.0.0" = {
      name = "parse-json";
      packageName = "parse-json";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-json/-/parse-json-4.0.0.tgz";
        sha1 = "be35f5425be1f7f6c747184f98a788cb99477ee0";
      };
    };
    "postcss-7.0.35" = {
      name = "postcss";
      packageName = "postcss";
      version = "7.0.35";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-7.0.35.tgz";
        sha512 = "3QT8bBJeX/S5zKTTjTCIjRF3If4avAT6kqxcASlTWEtAFCb9NH0OUxNDfgZSWdP5fJnBYCMEWkIFfWeugjzYMg==";
      };
    };
    "postcss-calc-7.0.5" = {
      name = "postcss-calc";
      packageName = "postcss-calc";
      version = "7.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-calc/-/postcss-calc-7.0.5.tgz";
        sha512 = "1tKHutbGtLtEZF6PT4JSihCHfIVldU72mZ8SdZHIYriIZ9fh9k9aWSppaT8rHsyI3dX+KSR+W+Ix9BMY3AODrg==";
      };
    };
    "postcss-colormin-4.0.3" = {
      name = "postcss-colormin";
      packageName = "postcss-colormin";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-colormin/-/postcss-colormin-4.0.3.tgz";
        sha512 = "WyQFAdDZpExQh32j0U0feWisZ0dmOtPl44qYmJKkq9xFWY3p+4qnRzCHeNrkeRhwPHz9bQ3mo0/yVkaply0MNw==";
      };
    };
    "postcss-convert-values-4.0.1" = {
      name = "postcss-convert-values";
      packageName = "postcss-convert-values";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-convert-values/-/postcss-convert-values-4.0.1.tgz";
        sha512 = "Kisdo1y77KUC0Jmn0OXU/COOJbzM8cImvw1ZFsBgBgMgb1iL23Zs/LXRe3r+EZqM3vGYKdQ2YJVQ5VkJI+zEJQ==";
      };
    };
    "postcss-discard-comments-4.0.2" = {
      name = "postcss-discard-comments";
      packageName = "postcss-discard-comments";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-discard-comments/-/postcss-discard-comments-4.0.2.tgz";
        sha512 = "RJutN259iuRf3IW7GZyLM5Sw4GLTOH8FmsXBnv8Ab/Tc2k4SR4qbV4DNbyyY4+Sjo362SyDmW2DQ7lBSChrpkg==";
      };
    };
    "postcss-discard-duplicates-4.0.2" = {
      name = "postcss-discard-duplicates";
      packageName = "postcss-discard-duplicates";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-discard-duplicates/-/postcss-discard-duplicates-4.0.2.tgz";
        sha512 = "ZNQfR1gPNAiXZhgENFfEglF93pciw0WxMkJeVmw8eF+JZBbMD7jp6C67GqJAXVZP2BWbOztKfbsdmMp/k8c6oQ==";
      };
    };
    "postcss-discard-empty-4.0.1" = {
      name = "postcss-discard-empty";
      packageName = "postcss-discard-empty";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-discard-empty/-/postcss-discard-empty-4.0.1.tgz";
        sha512 = "B9miTzbznhDjTfjvipfHoqbWKwd0Mj+/fL5s1QOz06wufguil+Xheo4XpOnc4NqKYBCNqqEzgPv2aPBIJLox0w==";
      };
    };
    "postcss-discard-overridden-4.0.1" = {
      name = "postcss-discard-overridden";
      packageName = "postcss-discard-overridden";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-discard-overridden/-/postcss-discard-overridden-4.0.1.tgz";
        sha512 = "IYY2bEDD7g1XM1IDEsUT4//iEYCxAmP5oDSFMVU/JVvT7gh+l4fmjciLqGgwjdWpQIdb0Che2VX00QObS5+cTg==";
      };
    };
    "postcss-merge-longhand-4.0.11" = {
      name = "postcss-merge-longhand";
      packageName = "postcss-merge-longhand";
      version = "4.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-merge-longhand/-/postcss-merge-longhand-4.0.11.tgz";
        sha512 = "alx/zmoeXvJjp7L4mxEMjh8lxVlDFX1gqWHzaaQewwMZiVhLo42TEClKaeHbRf6J7j82ZOdTJ808RtN0ZOZwvw==";
      };
    };
    "postcss-merge-rules-4.0.3" = {
      name = "postcss-merge-rules";
      packageName = "postcss-merge-rules";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-merge-rules/-/postcss-merge-rules-4.0.3.tgz";
        sha512 = "U7e3r1SbvYzO0Jr3UT/zKBVgYYyhAz0aitvGIYOYK5CPmkNih+WDSsS5tvPrJ8YMQYlEMvsZIiqmn7HdFUaeEQ==";
      };
    };
    "postcss-minify-font-values-4.0.2" = {
      name = "postcss-minify-font-values";
      packageName = "postcss-minify-font-values";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-minify-font-values/-/postcss-minify-font-values-4.0.2.tgz";
        sha512 = "j85oO6OnRU9zPf04+PZv1LYIYOprWm6IA6zkXkrJXyRveDEuQggG6tvoy8ir8ZwjLxLuGfNkCZEQG7zan+Hbtg==";
      };
    };
    "postcss-minify-gradients-4.0.2" = {
      name = "postcss-minify-gradients";
      packageName = "postcss-minify-gradients";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-minify-gradients/-/postcss-minify-gradients-4.0.2.tgz";
        sha512 = "qKPfwlONdcf/AndP1U8SJ/uzIJtowHlMaSioKzebAXSG4iJthlWC9iSWznQcX4f66gIWX44RSA841HTHj3wK+Q==";
      };
    };
    "postcss-minify-params-4.0.2" = {
      name = "postcss-minify-params";
      packageName = "postcss-minify-params";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-minify-params/-/postcss-minify-params-4.0.2.tgz";
        sha512 = "G7eWyzEx0xL4/wiBBJxJOz48zAKV2WG3iZOqVhPet/9geefm/Px5uo1fzlHu+DOjT+m0Mmiz3jkQzVHe6wxAWg==";
      };
    };
    "postcss-minify-selectors-4.0.2" = {
      name = "postcss-minify-selectors";
      packageName = "postcss-minify-selectors";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-minify-selectors/-/postcss-minify-selectors-4.0.2.tgz";
        sha512 = "D5S1iViljXBj9kflQo4YutWnJmwm8VvIsU1GeXJGiG9j8CIg9zs4voPMdQDUmIxetUOh60VilsNzCiAFTOqu3g==";
      };
    };
    "postcss-normalize-charset-4.0.1" = {
      name = "postcss-normalize-charset";
      packageName = "postcss-normalize-charset";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-charset/-/postcss-normalize-charset-4.0.1.tgz";
        sha512 = "gMXCrrlWh6G27U0hF3vNvR3w8I1s2wOBILvA87iNXaPvSNo5uZAMYsZG7XjCUf1eVxuPfyL4TJ7++SGZLc9A3g==";
      };
    };
    "postcss-normalize-display-values-4.0.2" = {
      name = "postcss-normalize-display-values";
      packageName = "postcss-normalize-display-values";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-display-values/-/postcss-normalize-display-values-4.0.2.tgz";
        sha512 = "3F2jcsaMW7+VtRMAqf/3m4cPFhPD3EFRgNs18u+k3lTJJlVe7d0YPO+bnwqo2xg8YiRpDXJI2u8A0wqJxMsQuQ==";
      };
    };
    "postcss-normalize-positions-4.0.2" = {
      name = "postcss-normalize-positions";
      packageName = "postcss-normalize-positions";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-positions/-/postcss-normalize-positions-4.0.2.tgz";
        sha512 = "Dlf3/9AxpxE+NF1fJxYDeggi5WwV35MXGFnnoccP/9qDtFrTArZ0D0R+iKcg5WsUd8nUYMIl8yXDCtcrT8JrdA==";
      };
    };
    "postcss-normalize-repeat-style-4.0.2" = {
      name = "postcss-normalize-repeat-style";
      packageName = "postcss-normalize-repeat-style";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-repeat-style/-/postcss-normalize-repeat-style-4.0.2.tgz";
        sha512 = "qvigdYYMpSuoFs3Is/f5nHdRLJN/ITA7huIoCyqqENJe9PvPmLhNLMu7QTjPdtnVf6OcYYO5SHonx4+fbJE1+Q==";
      };
    };
    "postcss-normalize-string-4.0.2" = {
      name = "postcss-normalize-string";
      packageName = "postcss-normalize-string";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-string/-/postcss-normalize-string-4.0.2.tgz";
        sha512 = "RrERod97Dnwqq49WNz8qo66ps0swYZDSb6rM57kN2J+aoyEAJfZ6bMx0sx/F9TIEX0xthPGCmeyiam/jXif0eA==";
      };
    };
    "postcss-normalize-timing-functions-4.0.2" = {
      name = "postcss-normalize-timing-functions";
      packageName = "postcss-normalize-timing-functions";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-timing-functions/-/postcss-normalize-timing-functions-4.0.2.tgz";
        sha512 = "acwJY95edP762e++00Ehq9L4sZCEcOPyaHwoaFOhIwWCDfik6YvqsYNxckee65JHLKzuNSSmAdxwD2Cud1Z54A==";
      };
    };
    "postcss-normalize-unicode-4.0.1" = {
      name = "postcss-normalize-unicode";
      packageName = "postcss-normalize-unicode";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-unicode/-/postcss-normalize-unicode-4.0.1.tgz";
        sha512 = "od18Uq2wCYn+vZ/qCOeutvHjB5jm57ToxRaMeNuf0nWVHaP9Hua56QyMF6fs/4FSUnVIw0CBPsU0K4LnBPwYwg==";
      };
    };
    "postcss-normalize-url-4.0.1" = {
      name = "postcss-normalize-url";
      packageName = "postcss-normalize-url";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-url/-/postcss-normalize-url-4.0.1.tgz";
        sha512 = "p5oVaF4+IHwu7VpMan/SSpmpYxcJMtkGppYf0VbdH5B6hN8YNmVyJLuY9FmLQTzY3fag5ESUUHDqM+heid0UVA==";
      };
    };
    "postcss-normalize-whitespace-4.0.2" = {
      name = "postcss-normalize-whitespace";
      packageName = "postcss-normalize-whitespace";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-whitespace/-/postcss-normalize-whitespace-4.0.2.tgz";
        sha512 = "tO8QIgrsI3p95r8fyqKV+ufKlSHh9hMJqACqbv2XknufqEDhDvbguXGBBqxw9nsQoXWf0qOqppziKJKHMD4GtA==";
      };
    };
    "postcss-ordered-values-4.1.2" = {
      name = "postcss-ordered-values";
      packageName = "postcss-ordered-values";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-ordered-values/-/postcss-ordered-values-4.1.2.tgz";
        sha512 = "2fCObh5UanxvSxeXrtLtlwVThBvHn6MQcu4ksNT2tsaV2Fg76R2CV98W7wNSlX+5/pFwEyaDwKLLoEV7uRybAw==";
      };
    };
    "postcss-reduce-initial-4.0.3" = {
      name = "postcss-reduce-initial";
      packageName = "postcss-reduce-initial";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-reduce-initial/-/postcss-reduce-initial-4.0.3.tgz";
        sha512 = "gKWmR5aUulSjbzOfD9AlJiHCGH6AEVLaM0AV+aSioxUDd16qXP1PCh8d1/BGVvpdWn8k/HiK7n6TjeoXN1F7DA==";
      };
    };
    "postcss-reduce-transforms-4.0.2" = {
      name = "postcss-reduce-transforms";
      packageName = "postcss-reduce-transforms";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-reduce-transforms/-/postcss-reduce-transforms-4.0.2.tgz";
        sha512 = "EEVig1Q2QJ4ELpJXMZR8Vt5DQx8/mo+dGWSR7vWXqcob2gQLyQGsionYcGKATXvQzMPn6DSN1vTN7yFximdIAg==";
      };
    };
    "postcss-selector-parser-3.1.2" = {
      name = "postcss-selector-parser";
      packageName = "postcss-selector-parser";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-selector-parser/-/postcss-selector-parser-3.1.2.tgz";
        sha512 = "h7fJ/5uWuRVyOtkO45pnt1Ih40CEleeyCHzipqAZO2e5H20g25Y48uYnFUiShvY4rZWNJ/Bib/KVPmanaCtOhA==";
      };
    };
    "postcss-selector-parser-6.0.4" = {
      name = "postcss-selector-parser";
      packageName = "postcss-selector-parser";
      version = "6.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-selector-parser/-/postcss-selector-parser-6.0.4.tgz";
        sha512 = "gjMeXBempyInaBqpp8gODmwZ52WaYsVOsfr4L4lDQ7n3ncD6mEyySiDtgzCT+NYC0mmeOLvtsF8iaEf0YT6dBw==";
      };
    };
    "postcss-svgo-4.0.2" = {
      name = "postcss-svgo";
      packageName = "postcss-svgo";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-svgo/-/postcss-svgo-4.0.2.tgz";
        sha512 = "C6wyjo3VwFm0QgBy+Fu7gCYOkCmgmClghO+pjcxvrcBKtiKt0uCF+hvbMO1fyv5BMImRK90SMb+dwUnfbGd+jw==";
      };
    };
    "postcss-unique-selectors-4.0.1" = {
      name = "postcss-unique-selectors";
      packageName = "postcss-unique-selectors";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-unique-selectors/-/postcss-unique-selectors-4.0.1.tgz";
        sha512 = "+JanVaryLo9QwZjKrmJgkI4Fn8SBgRO6WXQBJi7KiAVPlmxikB5Jzc4EvXMT2H0/m0RjrVVm9rGNhZddm/8Spg==";
      };
    };
    "postcss-value-parser-3.3.1" = {
      name = "postcss-value-parser";
      packageName = "postcss-value-parser";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-value-parser/-/postcss-value-parser-3.3.1.tgz";
        sha512 = "pISE66AbVkp4fDQ7VHBwRNXzAAKJjw4Vw7nWI/+Q3vuly7SNfgYXvm6i5IgFylHGK5sP/xHAbB7N49OS4gWNyQ==";
      };
    };
    "postcss-value-parser-4.1.0" = {
      name = "postcss-value-parser";
      packageName = "postcss-value-parser";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-value-parser/-/postcss-value-parser-4.1.0.tgz";
        sha512 = "97DXOFbQJhk71ne5/Mt6cOu6yxsSfM0QGQyl0L25Gca4yGWEGJaig7l7gbCX623VqTBNGLRLaVUCnNkcedlRSQ==";
      };
    };
    "q-1.5.1" = {
      name = "q";
      packageName = "q";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/q/-/q-1.5.1.tgz";
        sha1 = "7e32f75b41381291d04611f1bf14109ac00651d7";
      };
    };
    "resolve-from-3.0.0" = {
      name = "resolve-from";
      packageName = "resolve-from";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-from/-/resolve-from-3.0.0.tgz";
        sha1 = "b22c7af7d9d6881bc8b6e653335eebcb0a188748";
      };
    };
    "rgb-regex-1.0.1" = {
      name = "rgb-regex";
      packageName = "rgb-regex";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/rgb-regex/-/rgb-regex-1.0.1.tgz";
        sha1 = "c0e0d6882df0e23be254a475e8edd41915feaeb1";
      };
    };
    "rgba-regex-1.0.0" = {
      name = "rgba-regex";
      packageName = "rgba-regex";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/rgba-regex/-/rgba-regex-1.0.0.tgz";
        sha1 = "43374e2e2ca0968b0ef1523460b7d730ff22eeb3";
      };
    };
    "sax-1.2.4" = {
      name = "sax";
      packageName = "sax";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.2.4.tgz";
        sha512 = "NqVDv9TpANUjFm0N8uM5GxL36UgKi9/atZw+x7YFnQ8ckwFGKrl4xX4yWtrey3UJm5nP1kUbnYgLopqWNSRhWw==";
      };
    };
    "scheduler-0.20.1" = {
      name = "scheduler";
      packageName = "scheduler";
      version = "0.20.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/scheduler/-/scheduler-0.20.1.tgz";
        sha512 = "LKTe+2xNJBNxu/QhHvDR14wUXHRQbVY5ZOYpOGWRzhydZUqrLb2JBvLPY7cAqFmqrWuDED0Mjk7013SZiOz6Bw==";
      };
    };
    "simple-swizzle-0.2.2" = {
      name = "simple-swizzle";
      packageName = "simple-swizzle";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-swizzle/-/simple-swizzle-0.2.2.tgz";
        sha1 = "a4da6b635ffcccca33f70d17cb92592de95e557a";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "stable-0.1.8" = {
      name = "stable";
      packageName = "stable";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/stable/-/stable-0.1.8.tgz";
        sha512 = "ji9qxRnOVfcuLDySj9qzhGSEFVobyt1kIOSkj1qZzYLzq7Tos/oUUWvotUPQLlrsidqsK6tBH89Bc9kL5zHA6w==";
      };
    };
    "string.prototype.trimend-1.0.4" = {
      name = "string.prototype.trimend";
      packageName = "string.prototype.trimend";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimend/-/string.prototype.trimend-1.0.4.tgz";
        sha512 = "y9xCjw1P23Awk8EvTpcyL2NIr1j7wJ39f+k6lvRnSMz+mz9CGz9NYPelDk42kOz6+ql8xjfK8oYzy3jAP5QU5A==";
      };
    };
    "string.prototype.trimstart-1.0.4" = {
      name = "string.prototype.trimstart";
      packageName = "string.prototype.trimstart";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimstart/-/string.prototype.trimstart-1.0.4.tgz";
        sha512 = "jh6e984OBfvxS50tdY2nRZnoC5/mLFKOREQfw8t5yytkoUsJRNxvI/E39qu1sD0OtWI3OC0XgKSmcWwziwYuZw==";
      };
    };
    "stylehacks-4.0.3" = {
      name = "stylehacks";
      packageName = "stylehacks";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/stylehacks/-/stylehacks-4.0.3.tgz";
        sha512 = "7GlLk9JwlElY4Y6a/rmbH2MhVlTyVmiJd1PfTCqFaIBEGMYNsrO/v3SeGTdhBThLg4Z+NbOk/qFMwCa+J+3p/g==";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "supports-color-6.1.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-6.1.0.tgz";
        sha512 = "qe1jfm1Mg7Nq/NSh6XE24gPXROEVsWHxC1LIx//XNlD9iw7YZQGjZNjYN7xGaEG6iKdA8EtNFW6R0gjnVXp+wQ==";
      };
    };
    "svgo-1.3.2" = {
      name = "svgo";
      packageName = "svgo";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/svgo/-/svgo-1.3.2.tgz";
        sha512 = "yhy/sQYxR5BkC98CY7o31VGsg014AKLEPxdfhora76l36hD9Rdy5NZA/Ocn6yayNPgSamYdtX2rFJdcv07AYVw==";
      };
    };
    "timsort-0.3.0" = {
      name = "timsort";
      packageName = "timsort";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/timsort/-/timsort-0.3.0.tgz";
        sha1 = "405411a8e7e6339fe64db9a234de11dc31e02bd4";
      };
    };
    "uniq-1.0.1" = {
      name = "uniq";
      packageName = "uniq";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uniq/-/uniq-1.0.1.tgz";
        sha1 = "b31c5ae8254844a3a8281541ce2b04b865a734ff";
      };
    };
    "uniqs-2.0.0" = {
      name = "uniqs";
      packageName = "uniqs";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uniqs/-/uniqs-2.0.0.tgz";
        sha1 = "ffede4b36b25290696e6e165d4a59edb998e6b02";
      };
    };
    "unquote-1.1.1" = {
      name = "unquote";
      packageName = "unquote";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/unquote/-/unquote-1.1.1.tgz";
        sha1 = "8fded7324ec6e88a0ff8b905e7c098cdc086d544";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "util.promisify-1.0.1" = {
      name = "util.promisify";
      packageName = "util.promisify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/util.promisify/-/util.promisify-1.0.1.tgz";
        sha512 = "g9JpC/3He3bm38zsLupWryXHoEcS22YHthuPQSJdMy6KNrzIRzWqcsHzD/WUnqe45whVou4VIsPew37DoXWNrA==";
      };
    };
    "vendors-1.0.4" = {
      name = "vendors";
      packageName = "vendors";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/vendors/-/vendors-1.0.4.tgz";
        sha512 = "/juG65kTL4Cy2su4P8HjtkTxk6VmJDiOPBufWniqQ6wknac6jNiXS9vU+hO3wgusiyqWlzTbVHi0dyJqRONg3w==";
      };
    };
  };
in
{
  cssnano = nodeEnv.buildNodePackage {
    name = "cssnano";
    packageName = "cssnano";
    version = "4.1.10";
    src = fetchurl {
      url = "https://registry.npmjs.org/cssnano/-/cssnano-4.1.10.tgz";
      sha512 = "5wny+F6H4/8RgNlaqab4ktc3e0/blKutmq8yNlBFXA//nSFFAqAngjNVRzUvCgYROULmZZUoosL/KSoZo5aUaQ==";
    };
    dependencies = [
      sources."@types/q-1.5.4"
      sources."alphanum-sort-1.0.2"
      sources."ansi-styles-3.2.1"
      sources."argparse-1.0.10"
      sources."boolbase-1.0.0"
      sources."browserslist-4.16.3"
      sources."call-bind-1.0.2"
      sources."caller-callsite-2.0.0"
      sources."caller-path-2.0.0"
      sources."callsites-2.0.0"
      sources."caniuse-api-3.0.0"
      sources."caniuse-lite-1.0.30001192"
      sources."chalk-2.4.2"
      sources."coa-2.0.2"
      sources."color-3.1.3"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."color-string-1.5.4"
      sources."colorette-1.2.2"
      sources."cosmiconfig-5.2.1"
      sources."css-color-names-0.0.4"
      sources."css-declaration-sorter-4.0.1"
      sources."css-select-2.1.0"
      sources."css-select-base-adapter-0.1.1"
      sources."css-tree-1.0.0-alpha.37"
      sources."css-what-3.4.2"
      sources."cssesc-3.0.0"
      sources."cssnano-preset-default-4.0.7"
      sources."cssnano-util-get-arguments-4.0.0"
      sources."cssnano-util-get-match-4.0.0"
      sources."cssnano-util-raw-cache-4.0.1"
      sources."cssnano-util-same-parent-4.0.1"
      (sources."csso-4.2.0" // {
        dependencies = [
          sources."css-tree-1.1.2"
          sources."mdn-data-2.0.14"
        ];
      })
      sources."define-properties-1.1.3"
      (sources."dom-serializer-0.2.2" // {
        dependencies = [
          sources."domelementtype-2.1.0"
        ];
      })
      sources."domelementtype-1.3.1"
      sources."domutils-1.7.0"
      sources."dot-prop-5.3.0"
      sources."electron-to-chromium-1.3.674"
      sources."entities-2.2.0"
      sources."error-ex-1.3.2"
      sources."es-abstract-1.18.0-next.2"
      sources."es-to-primitive-1.2.1"
      sources."escalade-3.1.1"
      sources."escape-string-regexp-1.0.5"
      sources."esprima-4.0.1"
      sources."function-bind-1.1.1"
      sources."get-intrinsic-1.1.1"
      sources."has-1.0.3"
      sources."has-flag-3.0.0"
      sources."has-symbols-1.0.1"
      sources."hex-color-regex-1.1.0"
      sources."hsl-regex-1.0.0"
      sources."hsla-regex-1.0.0"
      sources."html-comment-regex-1.1.2"
      sources."import-fresh-2.0.0"
      sources."indexes-of-1.0.1"
      sources."is-absolute-url-2.1.0"
      sources."is-arrayish-0.2.1"
      sources."is-callable-1.2.3"
      sources."is-color-stop-1.1.0"
      sources."is-date-object-1.0.2"
      sources."is-directory-0.3.1"
      sources."is-negative-zero-2.0.1"
      sources."is-obj-2.0.0"
      sources."is-regex-1.1.2"
      sources."is-resolvable-1.1.0"
      sources."is-svg-3.0.0"
      sources."is-symbol-1.0.3"
      sources."js-yaml-3.14.1"
      sources."json-parse-better-errors-1.0.2"
      sources."lodash.memoize-4.1.2"
      sources."lodash.uniq-4.5.0"
      sources."mdn-data-2.0.4"
      sources."minimist-1.2.5"
      sources."mkdirp-0.5.5"
      sources."node-releases-1.1.71"
      sources."normalize-url-3.3.0"
      sources."nth-check-1.0.2"
      sources."object-inspect-1.9.0"
      sources."object-keys-1.1.1"
      sources."object.assign-4.1.2"
      sources."object.getownpropertydescriptors-2.1.2"
      sources."object.values-1.1.3"
      sources."parse-json-4.0.0"
      (sources."postcss-7.0.35" // {
        dependencies = [
          sources."supports-color-6.1.0"
        ];
      })
      sources."postcss-calc-7.0.5"
      (sources."postcss-colormin-4.0.3" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      (sources."postcss-convert-values-4.0.1" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      sources."postcss-discard-comments-4.0.2"
      sources."postcss-discard-duplicates-4.0.2"
      sources."postcss-discard-empty-4.0.1"
      sources."postcss-discard-overridden-4.0.1"
      (sources."postcss-merge-longhand-4.0.11" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      (sources."postcss-merge-rules-4.0.3" // {
        dependencies = [
          sources."postcss-selector-parser-3.1.2"
        ];
      })
      (sources."postcss-minify-font-values-4.0.2" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      (sources."postcss-minify-gradients-4.0.2" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      (sources."postcss-minify-params-4.0.2" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      (sources."postcss-minify-selectors-4.0.2" // {
        dependencies = [
          sources."postcss-selector-parser-3.1.2"
        ];
      })
      sources."postcss-normalize-charset-4.0.1"
      (sources."postcss-normalize-display-values-4.0.2" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      (sources."postcss-normalize-positions-4.0.2" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      (sources."postcss-normalize-repeat-style-4.0.2" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      (sources."postcss-normalize-string-4.0.2" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      (sources."postcss-normalize-timing-functions-4.0.2" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      (sources."postcss-normalize-unicode-4.0.1" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      (sources."postcss-normalize-url-4.0.1" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      (sources."postcss-normalize-whitespace-4.0.2" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      (sources."postcss-ordered-values-4.1.2" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      sources."postcss-reduce-initial-4.0.3"
      (sources."postcss-reduce-transforms-4.0.2" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      sources."postcss-selector-parser-6.0.4"
      (sources."postcss-svgo-4.0.2" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      sources."postcss-unique-selectors-4.0.1"
      sources."postcss-value-parser-4.1.0"
      sources."q-1.5.1"
      sources."resolve-from-3.0.0"
      sources."rgb-regex-1.0.1"
      sources."rgba-regex-1.0.0"
      sources."sax-1.2.4"
      (sources."simple-swizzle-0.2.2" // {
        dependencies = [
          sources."is-arrayish-0.3.2"
        ];
      })
      sources."source-map-0.6.1"
      sources."sprintf-js-1.0.3"
      sources."stable-0.1.8"
      sources."string.prototype.trimend-1.0.4"
      sources."string.prototype.trimstart-1.0.4"
      (sources."stylehacks-4.0.3" // {
        dependencies = [
          sources."postcss-selector-parser-3.1.2"
        ];
      })
      sources."supports-color-5.5.0"
      sources."svgo-1.3.2"
      sources."timsort-0.3.0"
      sources."uniq-1.0.1"
      sources."uniqs-2.0.0"
      sources."unquote-1.1.1"
      sources."util-deprecate-1.0.2"
      (sources."util.promisify-1.0.1" // {
        dependencies = [
          sources."es-abstract-1.17.7"
        ];
      })
      sources."vendors-1.0.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A modular minifier, built on top of the PostCSS ecosystem.";
      homepage = https://github.com/cssnano/cssnano;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  react = nodeEnv.buildNodePackage {
    name = "react";
    packageName = "react";
    version = "17.0.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/react/-/react-17.0.1.tgz";
      sha512 = "lG9c9UuMHdcAexXtigOZLX8exLWkW0Ku29qPRU8uhF2R9BN96dLCt0psvzPLlHc5OWkgymP3qwTRgbnw5BKx3w==";
    };
    dependencies = [
      sources."js-tokens-4.0.0"
      sources."loose-envify-1.4.0"
      sources."object-assign-4.1.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "React is a JavaScript library for building user interfaces.";
      homepage = https://reactjs.org/;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  react-dom = nodeEnv.buildNodePackage {
    name = "react-dom";
    packageName = "react-dom";
    version = "17.0.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/react-dom/-/react-dom-17.0.1.tgz";
      sha512 = "6eV150oJZ9U2t9svnsspTMrWNyHc6chX0KzDeAOXftRa8bNeOKTTfCJ7KorIwenkHd2xqVTBTCZd79yk/lx/Ug==";
    };
    dependencies = [
      sources."js-tokens-4.0.0"
      sources."loose-envify-1.4.0"
      sources."object-assign-4.1.1"
      sources."scheduler-0.20.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "React package for working with the DOM.";
      homepage = https://reactjs.org/;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "normalize.css" = nodeEnv.buildNodePackage {
    name = "normalize.css";
    packageName = "normalize.css";
    version = "8.0.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/normalize.css/-/normalize.css-8.0.1.tgz";
      sha512 = "qizSNPO93t1YUuUhP22btGOo3chcvDFqFaj2TRybP0DMxkHOCTYwp3n34fel4a31ORXy4m1Xq0Gyqpb5m33qIg==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "A modern alternative to CSS resets";
      homepage = https://necolas.github.io/normalize.css;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}