# This file has been generated by node2nix 1.7.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "loose-envify-1.4.0" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz";
        sha512 = "lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "prop-types-15.7.2" = {
      name = "prop-types";
      packageName = "prop-types";
      version = "15.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prop-types/-/prop-types-15.7.2.tgz";
        sha512 = "8QQikdH7//R2vurIJSutZ1smHYTcLpRWEOlHnzcWHmBYrOGUysKwSsrC89BCiFj3CbrfJ/nXFdJepOVrY1GCHQ==";
      };
    };
    "react-is-16.12.0" = {
      name = "react-is";
      packageName = "react-is";
      version = "16.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-is/-/react-is-16.12.0.tgz";
        sha512 = "rPCkf/mWBtKc97aLL9/txD8DZdemK0vkA3JMLShjlJB3Pj3s+lpf1KaBzMfQrAmhMQB0n1cU/SUGgKKBCe837Q==";
      };
    };
    "scheduler-0.18.0" = {
      name = "scheduler";
      packageName = "scheduler";
      version = "0.18.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/scheduler/-/scheduler-0.18.0.tgz";
        sha512 = "agTSHR1Nbfi6ulI0kYNK0203joW2Y5W4po4l+v03tOoiJKpTBbxpNhWDvqc/4IcOw+KLmSiQLTasZ4cab2/UWQ==";
      };
    };
  };
in
{
  react = nodeEnv.buildNodePackage {
    name = "react";
    packageName = "react";
    version = "16.12.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/react/-/react-16.12.0.tgz";
      sha512 = "fglqy3k5E+81pA8s+7K0/T3DBCF0ZDOher1elBFzF7O6arXJgzyu/FW+COxFvAWXJoJN9KIZbT2LXlukwphYTA==";
    };
    dependencies = [
      sources."js-tokens-4.0.0"
      sources."loose-envify-1.4.0"
      sources."object-assign-4.1.1"
      sources."prop-types-15.7.2"
      sources."react-is-16.12.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "React is a JavaScript library for building user interfaces.";
      homepage = https://reactjs.org/;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  react-dom = nodeEnv.buildNodePackage {
    name = "react-dom";
    packageName = "react-dom";
    version = "16.12.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/react-dom/-/react-dom-16.12.0.tgz";
      sha512 = "LMxFfAGrcS3kETtQaCkTKjMiifahaMySFDn71fZUNpPHZQEzmk/GiAeIT8JSOrHB23fnuCOMruL2a8NYlw+8Gw==";
    };
    dependencies = [
      sources."js-tokens-4.0.0"
      sources."loose-envify-1.4.0"
      sources."object-assign-4.1.1"
      sources."prop-types-15.7.2"
      sources."react-is-16.12.0"
      sources."scheduler-0.18.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "React package for working with the DOM.";
      homepage = https://reactjs.org/;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}